apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: inventory-service
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: inventory-service
      annotations:
        co.elastic.logs/enabled: "true"
        co.elastic.logs.json-logging/json.keys_under_root: "true"
        co.elastic.logs.json-logging/json.add_error_key: "true"
        co.elastic.logs.json-logging/json.message_key: "message"
    spec:
      containers:
      - image: springframeworkguru/kbe-brewery-inventory-service
        name: kbe-brewery-inventory-service
        resources: {}
        env:
          - name: SPRING_DATASOURCE_USER
            value: root
          - name: SPRING_DATASOURCE_PASSWORD
            value: dbpassword
          - name:  SPRING_JPA_HIBERNATE_DDL-AUTO
            value: update
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql:3306/beerservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
          - name: SPRING_ARTEMIS_HOST
            value: jms
          - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
            value: "true"
          - name: MANAGEMENT_HEALTH_READINESSTATE_ENABLED
            value: "true"
          - name: MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED
            value: "true"
          - name: SERVER_SHUTDOWN
            value: "graceful"
        readinessProbe:
          httpGet:
            port: 8082
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8082
            path: /actuator/health/liveness
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
status: {}






